repos:
  # Black formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2 # phiên bản black
    hooks:
      - id: black
        language_version: python3.12

  # isort formatter
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  # flake8 linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
