checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: outputs/checkpoints
  filename: ${user}_${experiment.name}_${experiment.encoder.model_name}_${experiment.datamodule.current_fold}_${now:%Y%m%d_%H%M%S}
  monitor: val/f1
  mode: max
  save_top_k: 1
  save_weights_only: true
  verbose: true
early_stop:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val/f1            
  mode: max                        
  patience: 5                     
  min_delta: 0.01                 
  verbose: true