_target_: src.datamodule.ent_crossval.CrossValENTDataModule

csv_file: data/data-filter.csv
image_dir: data/data-filter
batch_size: 32
num_workers: 4
image_size: 224
num_folds: 5
current_fold: 0
seed: 42