_target_: src.datamodule.ent_multitask.ENTMultiTaskDataModule
# Directory pointing to the fine-grained branch created by split_multitask.py
multitask_root: data/12endo_multitask/fine
batch_size: 3
num_workers: 4
image_size: 224
pin_memory: true
persistent_workers: true
